python/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path

from .swagger import urlpatterns as swagger_urlpatterns

handler404 = 'courses.core.views.error404'

urlpatterns = [
    # Django Admin
    re_path(settings.ADMIN_URL, admin.site.urls),
    # Courses core
    re_path(r'^', include('courses.core.url')),
]

# API
urlpatterns += [
    re_path(r'^api/', include('config.api_router')),
    re_path(r'^jwt/', include('config.auth')),
    re_path(r'^', include(swagger_urlpatterns)),
]

# Templates
urlpatterns += [
    re_path('^', include('courses.hls.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python/courses/hls/urls.py
from django.urls import re_path, path

from .views import IndexView, SubCategoryListView, CourseDetailView

app_name = 'hls'
urlpatterns = [
    re_path('^$', IndexView.as_view(), name='index'),
    path('courses/<str:subcategory>/', SubCategoryListView.as_view(),
         name='subcategory_detail'),
    path('course/<str:course>/', CourseDetailView.as_view(),
         name='course_detail'),
]

python/courses/core/api/views.py
from collections import OrderedDict

from django.http import FileResponse
from django.utils.decorators import method_decorator

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from rest_framework.permissions import IsAdminUser
from rest_framework.views import APIView

from courses.core.services import DocExporter
from courses.core.utils import file_from_bytes

from .renderers import XlsxRenderer


class DebugXlsxFileView(APIView):
    renderer_classes = (XlsxRenderer, )

    @method_decorator(decorator=swagger_auto_schema(
        tags=['debug'],
        operation_summary='Returns test xlsx file.',
        operation_description='Returns test xlsx file.',
        responses={
            200: openapi.TYPE_FILE,
        },
    ))
    def get(self, request):
        bytes_ = DocExporter.from_iterable(
            OrderedDict({
                'field1': 'TitleField1',
                'field2': 'TitleField2',
            }),
            [
                {
                    'field1': 'x**2',
                    'field2': 'y**3',
                },
                {
                    'field1': 'z**2',
                    'field2': 'w**3',
                },
            ],
        )

        doc = file_from_bytes(bytes_)

        response = FileResponse(doc)
        response['Content-Disposition'] = 'attachment; filename=test.xlsx'

        return response


class DebugTriggerError(APIView):
    permission_classes = (IsAdminUser, )

    @method_decorator(decorator=swagger_auto_schema(
        tags=['debug'],
        operation_summary='Trigger an error.',
        operation_description='Trigger an error.',
        responses={
            500: openapi.TYPE_STRING,
        },
    ))
    def get(self, request):
        impossible = 1 / 0 # noqa

python/courses/core/views.py
from django.db import connection
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt

from rest_framework import status


def error404(request, exception, *args, **kwargs):
    """
    Generic 404 error handler.
    """
    data = {
        'detail': 'Not found.',
    }
    return JsonResponse(data, status=status.HTTP_404_NOT_FOUND)


def index(request):
    return redirect('core:db-health')


@csrf_exempt
def echo(request):
    return JsonResponse(
        {
            'path': request.path,
            'method': request.method,
            'agent': request.headers.get('User-Agent'),
        },
    )


def db_health(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT 1')
        res = cursor.fetchone()
    return JsonResponse(
        {
            'status': res[0],
        },
    )

python/courses/hls/api/v1/views.py
from rest_framework.permissions import IsAuthenticated

from rest_framework.generics import ListAPIView

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from courses.core.api.paginations import StandardResultsSetPagination
from courses.hls.models import Category, Course


from .serializers import CategorySerializer, CourseSerializer


class CategoryListView(ListAPIView):
    permission_classes = (IsAuthenticated, )
    serializer_class = CategorySerializer
    queryset = Category.objects.all()
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        return self.queryset

    @swagger_auto_schema(
        tags=['hls'],
        operation_summary='Get hls courses categories.',
        operation_description='Get hls courses categories.',
        responses={
            200: openapi.Response('', CategorySerializer(many=True)),
        },
    )
    def get(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)


class CourseListView(ListAPIView):
    permission_classes = (IsAuthenticated, )
    serializer_class = CourseSerializer
    queryset = Course.objects.all()
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        return self.queryset.filter(category_id=self.kwargs.get('pk', 0))

    @swagger_auto_schema(
        tags=['hls'],
        operation_summary='Get hls courses.',
        operation_description='Get hls courses.',
        responses={
            200: openapi.Response('', CourseSerializer(many=True)),
        },
    )
    def get(self, request, pk, *args, **kwargs):
        return super().list(request, *args, **kwargs)

python/courses/hls/views.py
from django.views.generic import TemplateView, DetailView
from django.core import paginator

from .models import Category, Course, SubCategory


class IndexView(TemplateView):
    template_name = 'hls/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by('id').all()
        # SEO
        context['title'] = 'Видеокурсы по программированию'
        context['description'] = 'Видеокурсы по программированию'

        return context


class SubCategoryListView(DetailView):
    template_name = 'hls/subcategory_detail.html'

    model = SubCategory
    context_object_name = 'subcategory'
    slug_url_kwarg = 'subcategory'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by('id').all()

        context['is_paginated'] = True
        courses = Course.objects.filter(
            sub_category=kwargs['object'],
        ).order_by('id').select_related('sub_category')

        paging = paginator.Paginator(
                courses,
                self.request.GET.get('page_size', self.paginate_by),
            )
        try:
            context['courses'] = paging.page(self.request.GET.get('page', 1))
        except paginator.InvalidPage:
            context['courses'] = paging.page(1)

        # SEO
        context['title'] = 'Видеокурсы по программированию'
        context['description'] = 'Видеокурсы по программированию'

        return context


class CourseDetailView(DetailView):
    template_name = 'hls/course_detail.html'

    model = Course
    context_object_name = 'course'
    slug_url_kwarg = 'course'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by('id').all()

        context['title'] = 'Видеокурсы по программированию'
        context['description'] = 'Видеокурсы по программированию'

        return context

python/courses/users/api/v1/views.py
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.http.response import Http404

from django_filters import rest_framework as filters

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.generics import GenericAPIView
from rest_framework.generics import ListAPIView
from rest_framework.mixins import (
    CreateModelMixin,
    DestroyModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
)
from rest_framework.permissions import (
    AllowAny,
    IsAdminUser,
    IsAuthenticated,
)
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet

from courses.core.api.paginations import StandardResultsSetPagination
from courses.core.api.serializers import MessageSerializer
from courses.core.mixins import MessageResponseMixin
from courses.core.pyjwt import InvalidJWTTokenError
from courses.users.utils import (
    create_password_recovery_link,
    get_tokens_for_user,
    payload_from_token,
)

from .filters import UserFilter
from .permissions import IsAdminOrOwner
from .serializers import (
    AdminUserSerializer,
    CheckPasswordStrengthSerializer,
    CheckUsernameAvailabilitySerializer,
    RecoveryPasswordSerializer,
    RequestPasswordRecoveryEmailSerializer,
    UserRegistrationSerializer,
    UserSerializer,
)

User = get_user_model()


class CheckUsernameAvailabilityView(MessageResponseMixin, APIView):
    permission_classes = (AllowAny,)

    @swagger_auto_schema(
        tags=['jwt-auth', 'users', 'debug'],
        operation_summary='Check username availability',
        request_body=CheckUsernameAvailabilitySerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request):
        p = CheckUsernameAvailabilitySerializer(data=request.data)
        p.is_valid(raise_exception=True)
        return self.message_response(
            msg_data={
                'username': 'Username is available for registration',
            },
        )


class CheckPasswordStrengthView(MessageResponseMixin, APIView):
    permission_classes = (AllowAny,)

    @swagger_auto_schema(
        tags=['jwt-auth', 'users', 'debug'],
        operation_summary='Check password strength',
        request_body=CheckPasswordStrengthSerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request):
        p = CheckPasswordStrengthSerializer(data=request.data)
        p.is_valid(raise_exception=True)
        return self.message_response(
            msg_data={
                'password': 'Password is acceptable',
            },
        )


class UserRegistrationView(
    CreateModelMixin,
    GenericAPIView,
):
    serializer_class = UserRegistrationSerializer

    @swagger_auto_schema(
        tags=['jwt-auth', 'users'],
        operation_summary='Register user via password',
        operation_description='Register user via password',
    )
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class RequestPasswordRecoveryEmailView(MessageResponseMixin, APIView):
    """Test feature"""

    permission_classes = (AllowAny,)

    def get_object(self, email):
        try:
            return User.objects.get(email=email)
        except User.DoesNotExist:
            raise Http404

    @swagger_auto_schema(
        tags=['jwt-auth', 'users'],
        operation_summary='Request password recovery via link sended to email.',
        operation_description='Request password recovery'
                              ' via link sended to email.',
        request_body=RequestPasswordRecoveryEmailSerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request, *args, **kwargs):
        data = RequestPasswordRecoveryEmailSerializer(data=request.data)
        data.is_valid(raise_exception=True)

        user = self.get_object(data.validated_data['email'])
        send_mail(
            subject='Password recovery',
            message='To confirm password recovery'
                    ' click on the link below \n%s' % (
                        create_password_recovery_link(uid=user.id,
                                                      sub=user.email),
                    ),
            from_email='admin@gmail.com',
            recipient_list=[data.validated_data['email']],
        )

        return self.message_response(msg_data={
            'detail': 'Confirmation mail is sended',
        })


class RecoveryPasswordView(MessageResponseMixin, APIView):
    """Test feature"""

    permission_classes = (AllowAny,)

    def get_object(self, id_):
        try:
            return User.objects.get(id=id_)
        except User.DoesNotExist:
            raise Http404

    @swagger_auto_schema(
        tags=['jwt-auth', 'users'],
        operation_summary='Verify token and set new password.',
        operation_description='Verify token and set new password.',
        request_body=RecoveryPasswordSerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request, *args, **kwargs):
        data = RecoveryPasswordSerializer(data=request.data)
        data.is_valid(raise_exception=True)

        try:
            data.update(
                instance=self.get_object(
                    payload_from_token(
                        token=data.validated_data['token'])['uid'],
                ),
                validated_data=data.validated_data,
            )
        except InvalidJWTTokenError:
            return self.message_response(
                msg_data={
                    'detail': 'Token is invalid or expired',
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        return self.message_response(msg_data={
            'detail': 'Password successfully updated',
        })


class UserViewSet(
    RetrieveModelMixin,
    UpdateModelMixin,
    GenericViewSet,
):
    permission_classes = (
        IsAdminOrOwner,
        IsAuthenticated,
    )
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'id'

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Get my user profile.',
        operation_description='Get my user profile.',
        responses={
            200: openapi.Response('', UserSerializer),
        },
    )
    @action(detail=False, methods=['GET'])
    def me(self, request):
        serializer = UserSerializer(request.user, context={'request': request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Update user profile.',
        operation_description='Update user profile.',
    )
    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Patch update user profile.',
        operation_description='Patch update user profile.',
    )
    def partial_update(self, request, *args, **kwargs):
        return super().partial_update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Get user.',
        operation_description='Get user.',
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)


class AdminUserViewSet(
    DestroyModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
    CreateModelMixin,
    GenericViewSet,
):
    permission_classes = (IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = AdminUserSerializer
    lookup_field = 'id'

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Create user profile.',
        operation_description='Create user profile.',
    )
    def create(self, request, *args, **kwargs):
        return super().create(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Get my user profile.',
        operation_description='Get my user profile.',
        responses={
            200: openapi.Response('', AdminUserSerializer),
        },
    )
    @action(detail=False, methods=['GET'])
    def me(self, request):
        serializer = AdminUserSerializer(
            request.user, context={'request': request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Patch update user profile.',
        operation_description='Patch update user profile.',
    )
    def partial_update(self, request, *args, **kwargs):
        return super().partial_update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Update user profile.',
        operation_description='Update user profile.',
    )
    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Get user.',
        operation_description='Get user.',
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Delete user.',
        operation_description='Delete user.',
    )
    def destroy(self, request, *args, **kwargs):
        return super().destroy(request, *args, **kwargs)


class AdminUserListView(ListAPIView):
    permission_classes = (IsAdminUser,)
    queryset = User.objects.order_by('id').all()
    serializer_class = AdminUserSerializer

python/courses/templates/base/footer.html
{% load static %}
<!-- футер -->
<footer>
    <div class="container-fluid">
      <div class="row">
        <div class="col-0  col-sm-0  col-md-0  col-lg-3  col-xl-3">
          <p class="logo">course<span>hunter</span></p>
        </div>
        <div class="col-12  col-sm-6  col-md-4  col-lg-2  col-xl-2  footer_text_block">
          <h3>About Us</h3>
          <p>Mission</p>
          <p>Help Center</p>
          <p>Social Media</p>
        </div>
        <div class="col-12  col-sm-6  col-md-4  col-lg-2  col-xl-2 footer_text_block">
          <h3>Legal</h3>
          <p>Privacy Policy</p>
          <p>Help Center</p>
          <p>Social Media</p>
        </div>
        <div class="col-12  col-sm-6  col-md-4  col-lg-2  col-xl-2 footer_text_block">
          <h3>Follow Us</h3>
          <a href="">
          <div class="icon_timer_element">
            <i class="fa fa-instagram" aria-hidden="true"></i>
            <P> Instagram</P>
          </div></a>
          <a href="">
          <div class="icon_timer_element">
            <i class="fa fa-facebook" aria-hidden="true"></i>
            <P>Facebok</P>
          </div></a>
          <a href="">
          <div class="icon_timer_element">
            <i class="fa fa-linkedin" aria-hidden="true"></i>
            <P>Linkedin</P>
          </div></a>
        </div>
        <div class="col-12  col-sm-6  col-md-4  col-lg-3  col-xl-3 footer_text_block">
          <h3>Support</h3>
          <p>0 800 505 2020</p>
          <p>Mon-Fri: 9am to 8pm</p>
          <p>SWeekends: 12am to 7pm</p>
        </div>
      </div>

    </div>
    <div class="footer_bottom">
      <h3>© 2020 Name of the company. All Rights Reserved.</h3>
    </div>
</footer>

python/courses/templates/base/header.html
{% load static %}
<header>
  <div class="header_block">
    <div class="header_block_1">
      <div class="header_block_all header_block_logo">
        <p class="logo">pro<span>courses</span></p>
      </div>
      <div class="header_block_categories">

        <!-- выподающий список с категориями -->
        <nav>
          <ul class="topmenu">
            <li><a href="" class="active">Категории</a>
              <ul class="submenu navsubmenu">
                <!-- Список категорий -->
                <li><a href="">Javascript</a></li>
                <li><a href="" class="submenu-link">меню второго уровня</a>
                  <!-- Список подкатегорий -->
                  <ul class="submenu">
                    <li><a href="">SubMenu</a></li>
                    <li><a href="">Angular</a></li>
                    <li><a href="">React</a></li>
                  </ul>
                </li>
                <li><a href="">Python</a></li>
                <li><a href="" class="submenu-link">Java</a>
                  <!-- Список подкатегорий -->
                  <ul class="submenu">
                    <li><a href="">SubMenu</a></li>
                    <li><a href="">Angular</a></li>
                    <li><a href="">React</a></li>
                  </ul>
                </li>
                <li><a href="">Ruby</a></li>
                {% for category in categories %}
                  <li><a href="" class="submenu-link">{{ category.name }}</a>
                    <!-- Список подкатегорий -->
                    <ul class="submenu">
                      {% for sub in category.sub_categories.all %}
                        <li><a href="{% url 'hls:subcategory_detail' sub.slug %}">{{ sub.name }}</a></li>
                      {% endfor %}
                    </ul>
                  </li>
                {% endfor %}
              </ul>
            </li>
          </ul>
        </nav>

      </div>
      <div class="header_block_all header_block_sources">
        <a href="">Источники</a>
        <a href="">Все курсы</a>
      </div>
    </div>

    <div class="header_block_1">
      <div class="header_block_all header_block_search">
        <!-- поле поиска в хедере -->
        <div class="wrapper">
          <div class="wrapper_container">
            <input type="text" class="input" placeholder="Search">
            <i class="fa fa-search" aria-hidden="true"></i>
          </div>
        </div>

      </div>
      <div class="header_block_all header_block_signIn">
        <button type="button" class="btn btn-outline-danger">SignIn</button>
      </div>
    </div>

  </div>
</header>
<script>
    // скрипт анимации поиска в хедере
    $(".fa-search").click(function () {
      $(".wrapper_container, .input").toggleClass("active_search");
      $("input[type='text']").focus();
    });
</script>

python/courses/templates/base/layout.html
{% load static %}<!DOCTYPE html>
<html lang="ru-RU">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<title>PROGRAMMING</title>
	<title>{% block title %} {{ title }} {% endblock title %}</title>
	<link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}?v=2" sizes="16x16">

	  <!-- шрифты -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">

	<!-- Стили  -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<script src="https://use.fontawesome.com/221d038aca.js"></script>
	<link rel="stylesheet" href="{% static 'css/styleHome.css' %}">
	<link rel="stylesheet" href="{% static 'css/detailCourse.css' %}">
	<link rel="stylesheet" href="{% static 'css/styleCourse.css' %}">
	<link rel="stylesheet" href="{% static 'css/Global_style/global_style.css' %}">
	<!-- aded scripts Bootstrab and Jquery -->
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
	integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
	crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
	integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
	crossorigin="anonymous"></script>

    {% block css %}
    {% endblock %}

	{% block js %}
    {% endblock %}
</head>
<body>
	<div class="conteiner">
        {% include "base/header.html" %}

		{% block content %}
		{% endblock content %}

		{% include "base/footer.html" %}
	</div>
</body>
</html>