python/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path

from .swagger import urlpatterns as swagger_urlpatterns

handler404 = 'courses.core.views.error404'

urlpatterns = [
    # Django Admin
    re_path(settings.ADMIN_URL, admin.site.urls),
    # Courses core
    re_path(r'^', include('courses.core.url')),
]

# API
urlpatterns += [
    re_path(r'^api/', include('config.api_router')),
    re_path(r'^jwt/', include('config.auth')),
    re_path(r'^', include(swagger_urlpatterns)),
]

# Templates
urlpatterns += [
    re_path('^', include('courses.hls.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python/courses/hls/urls.py
from django.urls import re_path, path

from .views import IndexView, SubCategoryListView, CourseDetailView

app_name = 'hls'
urlpatterns = [
    re_path('^$', IndexView.as_view(), name='index'),
    path('courses/<str:subcategory>/', SubCategoryListView.as_view(),
         name='subcategory_detail'),
    path('course/<str:course>/', CourseDetailView.as_view(),
         name='course_detail'),
]

python/courses/core/api/views.py
from collections import OrderedDict

from django.http import FileResponse
from django.utils.decorators import method_decorator

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from rest_framework.permissions import IsAdminUser
from rest_framework.views import APIView

from courses.core.services import DocExporter
from courses.core.utils import file_from_bytes

from .renderers import XlsxRenderer


class DebugXlsxFileView(APIView):
    renderer_classes = (XlsxRenderer, )

    @method_decorator(decorator=swagger_auto_schema(
        tags=['debug'],
        operation_summary='Returns test xlsx file.',
        operation_description='Returns test xlsx file.',
        responses={
            200: openapi.TYPE_FILE,
        },
    ))
    def get(self, request):
        bytes_ = DocExporter.from_iterable(
            OrderedDict({
                'field1': 'TitleField1',
                'field2': 'TitleField2',
            }),
            [
                {
                    'field1': 'x**2',
                    'field2': 'y**3',
                },
                {
                    'field1': 'z**2',
                    'field2': 'w**3',
                },
            ],
        )

        doc = file_from_bytes(bytes_)

        response = FileResponse(doc)
        response['Content-Disposition'] = 'attachment; filename=test.xlsx'

        return response


class DebugTriggerError(APIView):
    permission_classes = (IsAdminUser, )

    @method_decorator(decorator=swagger_auto_schema(
        tags=['debug'],
        operation_summary='Trigger an error.',
        operation_description='Trigger an error.',
        responses={
            500: openapi.TYPE_STRING,
        },
    ))
    def get(self, request):
        impossible = 1 / 0 # noqa

python/courses/core/views.py
from django.db import connection
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt

from rest_framework import status


def error404(request, exception, *args, **kwargs):
    """
    Generic 404 error handler.
    """
    data = {
        'detail': 'Not found.',
    }
    return JsonResponse(data, status=status.HTTP_404_NOT_FOUND)


def index(request):
    return redirect('core:db-health')


@csrf_exempt
def echo(request):
    return JsonResponse(
        {
            'path': request.path,
            'method': request.method,
            'agent': request.headers.get('User-Agent'),
        },
    )


def db_health(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT 1')
        res = cursor.fetchone()
    return JsonResponse(
        {
            'status': res[0],
        },
    )

python/courses/hls/api/v1/views.py
from rest_framework.permissions import IsAuthenticated

from rest_framework.generics import ListAPIView

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from courses.core.api.paginations import StandardResultsSetPagination
from courses.hls.models import Category, Course


from .serializers import CategorySerializer, CourseSerializer


class CategoryListView(ListAPIView):
    permission_classes = (IsAuthenticated, )
    serializer_class = CategorySerializer
    queryset = Category.objects.all()
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        return self.queryset

    @swagger_auto_schema(
        tags=['hls'],
        operation_summary='Get hls courses categories.',
        operation_description='Get hls courses categories.',
        responses={
            200: openapi.Response('', CategorySerializer(many=True)),
        },
    )
    def get(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)


class CourseListView(ListAPIView):
    permission_classes = (IsAuthenticated, )
    serializer_class = CourseSerializer
    queryset = Course.objects.all()
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        return self.queryset.filter(category_id=self.kwargs.get('pk', 0))

    @swagger_auto_schema(
        tags=['hls'],
        operation_summary='Get hls courses.',
        operation_description='Get hls courses.',
        responses={
            200: openapi.Response('', CourseSerializer(many=True)),
        },
    )
    def get(self, request, pk, *args, **kwargs):
        return super().list(request, *args, **kwargs)

python/courses/hls/views.py
from django.views.generic import TemplateView, DetailView
from django.core import paginator

from .models import Category, Course, SubCategory


class IndexView(TemplateView):
    template_name = 'hls/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by('id').all()
        # SEO
        context['title'] = 'Видеокурсы по программированию'
        context['description'] = 'Видеокурсы по программированию'

        return context


class SubCategoryListView(DetailView):
    template_name = 'hls/subcategory_detail.html'

    model = SubCategory
    context_object_name = 'subcategory'
    slug_url_kwarg = 'subcategory'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by('id').all()

        context['is_paginated'] = True
        courses = Course.objects.filter(
            sub_category=kwargs['object'],
        ).order_by('id').select_related('sub_category')

        paging = paginator.Paginator(
                courses,
                self.request.GET.get('page_size', self.paginate_by),
            )
        try:
            context['courses'] = paging.page(self.request.GET.get('page', 1))
        except paginator.InvalidPage:
            context['courses'] = paging.page(1)

        # SEO
        context['title'] = 'Видеокурсы по программированию'
        context['description'] = 'Видеокурсы по программированию'

        return context


class CourseDetailView(DetailView):
    template_name = 'hls/course_detail.html'

    model = Course
    context_object_name = 'course'
    slug_url_kwarg = 'course'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.order_by('id').all()

        context['title'] = 'Видеокурсы по программированию'
        context['description'] = 'Видеокурсы по программированию'

        return context

python/courses/users/api/v1/views.py
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.http.response import Http404

from django_filters import rest_framework as filters

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.generics import GenericAPIView
from rest_framework.generics import ListAPIView
from rest_framework.mixins import (
    CreateModelMixin,
    DestroyModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
)
from rest_framework.permissions import (
    AllowAny,
    IsAdminUser,
    IsAuthenticated,
)
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet

from courses.core.api.paginations import StandardResultsSetPagination
from courses.core.api.serializers import MessageSerializer
from courses.core.mixins import MessageResponseMixin
from courses.core.pyjwt import InvalidJWTTokenError
from courses.users.utils import (
    create_password_recovery_link,
    get_tokens_for_user,
    payload_from_token,
)

from .filters import UserFilter
from .permissions import IsAdminOrOwner
from .serializers import (
    AdminUserSerializer,
    CheckPasswordStrengthSerializer,
    CheckUsernameAvailabilitySerializer,
    RecoveryPasswordSerializer,
    RequestPasswordRecoveryEmailSerializer,
    UserRegistrationSerializer,
    UserSerializer,
)

User = get_user_model()


class CheckUsernameAvailabilityView(MessageResponseMixin, APIView):
    permission_classes = (AllowAny,)

    @swagger_auto_schema(
        tags=['jwt-auth', 'users', 'debug'],
        operation_summary='Check username availability',
        request_body=CheckUsernameAvailabilitySerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request):
        p = CheckUsernameAvailabilitySerializer(data=request.data)
        p.is_valid(raise_exception=True)
        return self.message_response(
            msg_data={
                'username': 'Username is available for registration',
            },
        )


class CheckPasswordStrengthView(MessageResponseMixin, APIView):
    permission_classes = (AllowAny,)

    @swagger_auto_schema(
        tags=['jwt-auth', 'users', 'debug'],
        operation_summary='Check password strength',
        request_body=CheckPasswordStrengthSerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request):
        p = CheckPasswordStrengthSerializer(data=request.data)
        p.is_valid(raise_exception=True)
        return self.message_response(
            msg_data={
                'password': 'Password is acceptable',
            },
        )


class UserRegistrationView(
    CreateModelMixin,
    GenericAPIView,
):
    serializer_class = UserRegistrationSerializer

    @swagger_auto_schema(
        tags=['jwt-auth', 'users'],
        operation_summary='Register user via password',
        operation_description='Register user via password',
    )
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class RequestPasswordRecoveryEmailView(MessageResponseMixin, APIView):
    """Test feature"""

    permission_classes = (AllowAny,)

    def get_object(self, email):
        try:
            return User.objects.get(email=email)
        except User.DoesNotExist:
            raise Http404

    @swagger_auto_schema(
        tags=['jwt-auth', 'users'],
        operation_summary='Request password recovery via link sended to email.',
        operation_description='Request password recovery'
                              ' via link sended to email.',
        request_body=RequestPasswordRecoveryEmailSerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request, *args, **kwargs):
        data = RequestPasswordRecoveryEmailSerializer(data=request.data)
        data.is_valid(raise_exception=True)

        user = self.get_object(data.validated_data['email'])
        send_mail(
            subject='Password recovery',
            message='To confirm password recovery'
                    ' click on the link below \n%s' % (
                        create_password_recovery_link(uid=user.id,
                                                      sub=user.email),
                    ),
            from_email='admin@gmail.com',
            recipient_list=[data.validated_data['email']],
        )

        return self.message_response(msg_data={
            'detail': 'Confirmation mail is sended',
        })


class RecoveryPasswordView(MessageResponseMixin, APIView):
    """Test feature"""

    permission_classes = (AllowAny,)

    def get_object(self, id_):
        try:
            return User.objects.get(id=id_)
        except User.DoesNotExist:
            raise Http404

    @swagger_auto_schema(
        tags=['jwt-auth', 'users'],
        operation_summary='Verify token and set new password.',
        operation_description='Verify token and set new password.',
        request_body=RecoveryPasswordSerializer,
        responses={
            200: openapi.Response('', MessageSerializer),
        },
    )
    def post(self, request, *args, **kwargs):
        data = RecoveryPasswordSerializer(data=request.data)
        data.is_valid(raise_exception=True)

        try:
            data.update(
                instance=self.get_object(
                    payload_from_token(
                        token=data.validated_data['token'])['uid'],
                ),
                validated_data=data.validated_data,
            )
        except InvalidJWTTokenError:
            return self.message_response(
                msg_data={
                    'detail': 'Token is invalid or expired',
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        return self.message_response(msg_data={
            'detail': 'Password successfully updated',
        })


class UserViewSet(
    RetrieveModelMixin,
    UpdateModelMixin,
    GenericViewSet,
):
    permission_classes = (
        IsAdminOrOwner,
        IsAuthenticated,
    )
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'id'

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Get my user profile.',
        operation_description='Get my user profile.',
        responses={
            200: openapi.Response('', UserSerializer),
        },
    )
    @action(detail=False, methods=['GET'])
    def me(self, request):
        serializer = UserSerializer(request.user, context={'request': request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Update user profile.',
        operation_description='Update user profile.',
    )
    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Patch update user profile.',
        operation_description='Patch update user profile.',
    )
    def partial_update(self, request, *args, **kwargs):
        return super().partial_update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['users'],
        operation_summary='Get user.',
        operation_description='Get user.',
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)


class AdminUserViewSet(
    DestroyModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
    CreateModelMixin,
    GenericViewSet,
):
    permission_classes = (IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = AdminUserSerializer
    lookup_field = 'id'

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Create user profile.',
        operation_description='Create user profile.',
    )
    def create(self, request, *args, **kwargs):
        return super().create(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Get my user profile.',
        operation_description='Get my user profile.',
        responses={
            200: openapi.Response('', AdminUserSerializer),
        },
    )
    @action(detail=False, methods=['GET'])
    def me(self, request):
        serializer = AdminUserSerializer(
            request.user, context={'request': request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Patch update user profile.',
        operation_description='Patch update user profile.',
    )
    def partial_update(self, request, *args, **kwargs):
        return super().partial_update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Update user profile.',
        operation_description='Update user profile.',
    )
    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Get user.',
        operation_description='Get user.',
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)

    @swagger_auto_schema(
        tags=['admin-users'],
        operation_summary='Delete user.',
        operation_description='Delete user.',
    )
    def destroy(self, request, *args, **kwargs):
        return super().destroy(request, *args, **kwargs)


class AdminUserListView(ListAPIView):
    permission_classes = (IsAdminUser,)
    queryset = User.objects.order_by('id').all()
    serializer_class = AdminUserSerializer

python/courses/templates/hls/subcategory_detail.html
{% extends "base/layout.html" %}

{% load static %}

{% block content %}
<div class="course_title_desc">
    <div class="conteiner_padding">
        <div class="title_link_course">
            <a href="#" class="course_link">Главная страница</a>
            <a href="#">{{ subcategory.category.name }}</a>
            <a href="#">{{ subcategory.name }}</a>
        </div>
        <h2 class="title_course_choise">Видеоуроки {{ subcategory.name }}</h2>
        <div class="description_course">
          <div class="row">
            <div class="col-12  col-sm-4  col-md-4  col-lg-1  col-xl-1">
              <img src="{{ subcategory.icon.url }}" alt="" class="icon_course_description">
            </div>
            <div class="col-12  col-sm-8  col-md-8  col-lg-11  col-xl-11 relative">
              <p class="course_description">{{ subcategory.description }}</p>
            </div>

          </div>

        </div>
         <!-- блок с фильтрацией и кнопками выбора курсов -->
        <div class="filtr_course">
    <button type="button" class="btn btn-dark">Все</button>
    <button type="button" class="btn btn-dark">Angular</button>
    <button type="button" class="btn btn-dark">HTML</button>
    <button type="button" class="btn btn-dark">CSS</button>
    <button type="button" class="btn btn-dark">FavaScript</button>
    <button type="button" class="btn btn-dark">React</button>
    <button type="button" class="btn btn-dark">Jquery</button>
    <button type="button" class="btn btn-dark">Typescript</button>
    </div>
    </div>
</div>

<!-- блок курсы с выбранной категории  -->
<div class="after_course">
    <div class="container-fluid">
      <div class="row">
        {% for course in courses %}
          <!-- элемент в блоке -->
          <div class="col-12  col-sm-6  col-md-4  col-lg-12  col-xl-12 after_course_element ">
            <div class="row">
              <div class="col-12  col-sm-12  col-md-12  col-lg-4  col-xl-4 course_image_conteiner">
                <img src="{{ course.icon.url }}" alt="" class="course_image">

              </div>
              <div class="col-12  col-sm-12  col-md-12  col-lg-8  col-xl-8">
                <div class="title_raiting_star">
                  <h2 class="title_course_name">{{ course.name }}</h2>
                  <div class="reiting_star">
                    <div class="icon_star">
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>

                    </div>
                    <p>Голосов:1 | 1/0</p>
                  </div>
                </div>
                <p class="description">{{ course.name }}</p>
                <p class="description">{{ course.description | truncatechars:200 }}</p>
                <div class="bottom_flex_span_course">
                  <div class="icon_timer">
                    <div class="icon_timer_element">
                      <i class="fa fa-clock-o" aria-hidden="true"></i>
                      <P> 00:57:58</P>
                    </div>
                    <div class="icon_timer_element">
                      <i class="fa fa-play-circle-o" aria-hidden="true"></i>
                      <P> 40 уроков</P>
                    </div>
                    <div class="icon_timer_element">
                      <i class="fa fa-globe" aria-hidden="true"></i>
                      <P> English</P>
                    </div>
                    <a href="">
                      <div class="icon_timer_element">
                        <i class="fa fa-book" aria-hidden="true"></i>
                        <P> Udemy</P>
                      </div>
                    </a>

                  </div>
                  <a href="{% url 'hls:course_detail' course.slug %}" >
                    <button type="button" class="btn btn-primary">Посмотреть</button>
                  </a>
                </div>
              </div>


            </div>

          </div>
        {% endfor %}
        <!-- элемент в блоке -->
        <div class="col-12  col-sm-6  col-md-4  col-lg-12  col-xl-12 after_course_element ">
          <div class="row">
            <div class="col-12  col-sm-12  col-md-12  col-lg-4  col-xl-4 course_image_conteiner">
              <img src="{% static 'img/img_course_categories/cypress.jfif' %}" alt="" class="course_image">

            </div>
            <div class="col-12  col-sm-12  col-md-12  col-lg-8  col-xl-8">
              <div class="title_raiting_star">
                <h2 class="title_course_name">CYPRESS: АВТОМАТИЗАЦИЯ ТЕСТИРОВАНИЯ ДЛЯ ТЕХ КТО ТОРОПИТСЯ</h2>
                <div class="reiting_star">
                  <div class="icon_star">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>

                  </div>
                  <p>Голосов:1 | 1/0</p>
                </div>
              </div>
              <p class="description">Cypress test automation for people in a hurry</p>
              <p class="description">Этот курс предназначен для тестировщиков, инженеров по автоматизации и веб-разработчиков, которым необходимо быстро выучиться. Если вы начинаете с нуля или уже знакомы с автоматизацией тестирования, тогда этот курс для вас. Он заполнен краткими пояснительными видео, без лишних слов, только с практическими материалами.</p>
              <div class="bottom_flex_span_course">
                <div class="icon_timer">
                  <div class="icon_timer_element">
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    <P> 00:57:58</P>
                  </div>
                  <div class="icon_timer_element">
                    <i class="fa fa-play-circle-o" aria-hidden="true"></i>
                    <P> 40 уроков</P>
                  </div>
                  <div class="icon_timer_element">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                    <P> English</P>
                  </div>
                  <a href="">
                    <div class="icon_timer_element">
                      <i class="fa fa-book" aria-hidden="true"></i>
                      <P> Udemy</P>
                    </div>
                  </a>

                </div>
                <button type="button" class="btn btn-primary">Посмотреть</button>
              </div>
            </div>


          </div>

        </div>
        <!-- элемент в блоке -->
        <div class="col-12  col-sm-6  col-md-4  col-lg-12  col-xl-12 after_course_element ">
          <div class="row">
            <div class="col-12  col-sm-12  col-md-12  col-lg-4  col-xl-4 course_image_conteiner">
              <img src="{% static 'img/img_course_categories/react.jfif' %}" alt="" class="course_image">

            </div>
            <div class="col-12  col-sm-12  col-md-12  col-lg-8  col-xl-8">
              <div class="title_raiting_star">
                <h2 class="title_course_name">ТЕСТИРОВАНИЕ ПРИЛОЖЕНИЙ REACT C RTL</h2>
                <div class="reiting_star">
                  <div class="icon_star">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o " aria-hidden="true"></i>
                    <i class="fa fa-star-o " aria-hidden="true"></i>

                  </div>
                  <p>Голосов:3 | 2/1</p>
                </div>
              </div>
              <p class="description">Cypress test automation for people in a hurry</p>
              <p class="description">Этот курс предназначен для тестировщиков, инженеров по автоматизации и веб-разработчиков, которым необходимо быстро выучиться. Если вы начинаете с нуля или уже знакомы с автоматизацией тестирования, тогда этот курс для вас. Он заполнен краткими пояснительными видео, без лишних слов, только с практическими материалами.</p>
              <div class="bottom_flex_span_course">
                <div class="icon_timer">
                  <div class="icon_timer_element">
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    <P>  02:36:25</P>
                  </div>
                  <div class="icon_timer_element">
                    <i class="fa fa-play-circle-o" aria-hidden="true"></i>
                    <P> 21 уроков</P>
                  </div>
                  <div class="icon_timer_element">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                    <P> English</P>
                  </div>
                  <a href="">
                    <div class="icon_timer_element">
                      <i class="fa fa-book" aria-hidden="true"></i>
                      <P> Udemy</P>
                    </div>
                  </a>

                </div>
                <button type="button" class="btn btn-primary">Посмотреть</button>
              </div>
            </div>


          </div>

        </div>
      </div>
      <!-- пагинация  -->
      <nav aria-label="...">
        <ul class="pagination pagination-sm nav">
          <li class="page-item active_numberpage"><a class="page-link" href="#"></a>1</a>
          </li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">4</a></li>
          <li class="page-item"><a class="page-link" href="#">5</a></li>
          <li class="page-item"><a class="page-link" href="#">...</a></li>
          <li class="page-item"><a class="page-link" href="#">50</a></li>
        </ul>
      </nav>
    </div>
</div>

{% endblock content %}